#!/bin/bash
# Ask the user for login details
read -p 'Username: ' USERNAME
read -sp 'Password: ' PASSWORD
cat <<EOF > .env
# This file was generated by the prepare.sh script
VRC_USERNAME="$USERNAME"
VRC_PASSWORD="$PASSWORD"
EOF
echo "Your .env file has been generated."
